### ISSUE TITLE
envs_per_worker

### ISSUE THREAD

**Issue by Meta-YZ** [ingambe/RayEnvWrapper#1]
Hi！@ingambe. Thank you very much for your work! I have some questions. What does the "worker and envs" mean here? My understanding is as follows:

- Worker represents a process. Two env in a worker belong to two threads.

I don't know if I understand this correctly. Thanks!
![image](https://user-images.githubusercontent.com/68255669/162398237-b8b630d7-a00a-4450-b2fe-a0e7a962190f.png)

**Comment by ingambe** [comment]
Hi @Meta-YZ,
Each worker is a process, but sometimes having only one environment per worker (i.e., process) is not optimum. You might pay too much of a communication cost if the environment runs fast.
The total time for one step can be computed as: 
time to start workers + time to perform environment step on the workers + time to join
If the time to start + join is higher than the time to perform the step, it is a performance bottleneck. It happens in simple environments.

The wrapper allows you to run multiple sequential environments in the same worker (i.e., multiple environments in the same process). So each worker will run multiple environments sequentially. This way, the time to start and join stays fixed, but the time to perform the step increase, and you get more observations.

**Comment by Meta-YZ** [comment]
> 

Thanks！I got it!
